package actions

const (
	// HEALTH
	PLAYER_HEALTH  = 100
	MONSTER_HEALTH = 100

	// PLAYER GAME VALUES
	PLAYER_ATTACK_MIN_DMG         = 5
	PLAYER_ATTACK_MAX_DMG         = 10
	PLAYER_SPECIAL_ATTACK_MIN_DMG = 10
	PLAYER_SPECIAL_ATTACK_MAX_DMG = 20
	PLAYER_HEAL_MIN_VALUE         = 10
	PLAYER_HEAL_MAX_VALUE         = 20

	// MONSTER GAME VALUES
	MONSTER_ATTACK_MIN_DMG = 9
	MONSTER_ATTACK_MAX_DMG = 13
)
